image:
  repository: gcr.io/forgerock-io/amster
  #repository: gcr.io/engineering-devops/amster
  tag: 6.5.1
  pullPolicy: Always
  
config:
  importPath: /git/config/6.5/default/am/empty-import
  exportPath: /tmp/amster

ctsStores: ctsstore-0.ctsstore:1389,ctsstore-1.ctsstore:1389
ctsPassword: password

# For production set CPU limits to help Kube Schedule the pods.
resources:
 limits:
   memory: 756Mi
 requests:
   memory: 756Mi
