# Note if you enable TLS then you have to either provide the certificate 
# by running generate-tls.sh script or you have to have cert-manager deployed
# for your DNS domain 

#domain: freng.org
domain: test.net1

# Install passwords.
amadminPassword: password
encryptionKey: "123456789012"
policyAgentPassword: Passw0rd
